
import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "./BlogCard";
import SearchBar from "./SearchBar";
import Link from "next/link";
import { useState } from "react";




const graphcms = new GraphQLClient(
  "https://api-ap-south-1.hygraph.com/v2/clejz1pne0v3h01uo2sgo5ben/master"
);


const QUERY = gql`
  {
    posts {
      id
      title
      slug
      content
      author {
        name
        avatar {
          url
        }
      }
      image {
        publishedAt
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: any) {
const [searchTerm, setSearchTerm] = useState("")
  
  
  return (
    <>
      <Head>
        <title>AuthCrud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div>
      <div className="text-5xl text-blue-700 flex justify-center p-5 font-bold hover:scale-90 duration-300 hover:text-[#2B3467]">
        AuthCRUD
      </div>
      <div>
        <SearchBar func={(e:any)=> setSearchTerm(e.target.value)}/>
      </div>
      {posts.filter((val:any)=> {
      if(searchTerm === ""){
        return val
      }else if (val.content.toLowerCase().includes(searchTerm.toLowerCase())) {
        return val
      }
      
    }
    ).map((post: any) => {
        return (
          <div key={post.id}>
            <Link
              href={`post/${post.slug}`}
              className="blog-card flex justify-center p-5"
            >
              <BlogCard title={post.title} content={post.content} />
            </Link>
          </div>
        );
      })}
    </div>
      </main>
    </>
  );
}
